name: 构建并推送Docker镜像

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: 设置时区
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: 登录DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 生成Docker元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=match,pattern=^v(\d{8}-\d+)$,group=1
            type=match,pattern=^v(\d{8})-\d+$,group=1
            type=raw,value=ci-{{commit_date 'YYYYMMDD-HHmmss' tz='Asia/Shanghai'}}-{{sha}},enable=${{ github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建并推送镜像
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
