name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get current date
        id: current_date
        run: |
          export TZ=Asia/Shanghai # 设置时区为中国标准时间（UTC+8）
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV # 获取当前日期并存储在环境变量中

      - name: Build the Docker image
        run: docker build -t mateoust/autopcr:${{ env.CURRENT_DATE }} .

      - name: Push the Docker image to Docker Hub
        run: docker push mateoust/autopcr:${{ env.CURRENT_DATE }}

      - name: Save Docker image as a tar file
        run: docker save -o ${GITHUB_WORKSPACE}/docker-image.tar mateoust/${{ env.CURRENT_DATE }}
        
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar
